Repository Gongjakso/server, pull requests merged in 2024-05, with the labels that each got.

#126 feat: 페이지네이션 시작 인덱스 변경
  src/main/java/com/gongjakso/server/ServerApplication.java
Labels: feat

#129 refactor: 시/분/초 제거 로직을 도입하기 위해, Reqeust DTO 임시로 포맷팅 진행
  src/main/java/com/gongjakso/server/domain/apply/dto/PeriodReq.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: refactor

#131 fix: Post 리팩토링 및 공고 목록 조회, 내가 스크랩한 공고 조회 API 오류 해결
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostScrapRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix, refactor

#133 #132 refactor : post status가 active인 공고만 노출
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#136 fix: 검색어 공백 제거 코드 삭제
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#140 feat: 공고 카테고리 별 인원 및 전체 인원 확인 로직 추가
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: feat

#141 fix: 공고 상세 조회 엔드포인트 및 DTO 수정
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostDetailRes.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#142 fix: QA사항 업데이트
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostScrapRes.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix, refactor

#143 fix: qa 사항 업데이트
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/PostStatus.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#146 fix: 정렬 기준을 생성 시각 기준 내림차순으로 적용 관련 오류 수정
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#147 fix: 카테고리별 지원자 수 확인 조건 수정
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#148 fix: QA 사항 수정
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#149 fix: 쿼리 오류 수정
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#151 feat: 활동 완료 API
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/test/java/com/gongjakso/server/domain/post/service/PostServiceTest.java
Labels: feat

#152 feat: 활동 완료 API
  src/main/java/com/gongjakso/server/domain/post/dto/PostSimpleRes.java
  src/test/java/com/gongjakso/server/domain/post/util/PostUtilTest.java
Labels: feat

#153 fix: 내가 참여한 팀 조회 API 비즈니스 로직 수정
  src/main/java/com/gongjakso/server/domain/apply/dto/ParticipationList.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
Labels: fix

#154 fix: QA 사항 업데이트
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ParticipationList.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#156 fix: 내가 모집중인 팀 조회 쿼리 수정
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#157 refactor: pagination과 fetch join간의 문제점 해결하기 위한 쿼리 튜닝 진행
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
Labels: fix, refactor

#158 refactor: pagination과 fetch join간의 문제점 해결하기 위한 쿼리 튜닝 진행
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
Labels: fix, refactor

#155 test: 스크랩 관련 Domain, Service 유닛 테스트 코드 작성
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/member/entity/Member.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/entity/PostScrap.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostScrapRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
  src/test/java/com/gongjakso/server/domain/member/util/MemberUtilTest.java
  src/test/java/com/gongjakso/server/domain/post/controller/PaginationControllerTest.java
  src/test/java/com/gongjakso/server/domain/post/domain/ScrapDomainTest.java
  src/test/java/com/gongjakso/server/domain/post/service/PaginationServiceTest.java
  src/test/java/com/gongjakso/server/domain/post/service/PostServiceTest.java
  src/test/java/com/gongjakso/server/domain/post/util/PostScrapUtilTest.java
  src/test/java/com/gongjakso/server/domain/post/util/PostUtilTest.java
Labels: test
