Repository Gongjakso/server, pull requests merged in 2024-08, with the labels that each got.

#174 #171 feat : contest entity
  src/main/java/com/gongjakso/server/domain/contest/entity/Contest.java
Labels: feat

#176 chore: Workflow에서 해당 경로 인지를 위한 gitkeep 파일 적용
  src/main/resources/.gitkeep
Labels: fix, chore

#179 fix: 카카오 로그인 관련 로직 업데이트
  src/main/java/com/gongjakso/server/domain/member/controller/AuthController.java
  src/main/java/com/gongjakso/server/domain/member/service/AuthService.java
  src/main/java/com/gongjakso/server/global/security/kakao/KakaoClient.java
Labels: fix

#177 feat : contest api 구현
  src/main/java/com/gongjakso/server/domain/contest/controller/ContestController.java
  src/main/java/com/gongjakso/server/domain/contest/dto/request/ContestReq.java
  src/main/java/com/gongjakso/server/domain/contest/dto/request/UpdateContestDto.java
  src/main/java/com/gongjakso/server/domain/contest/dto/response/ContestCard.java
  src/main/java/com/gongjakso/server/domain/contest/dto/response/ContestListRes.java
  src/main/java/com/gongjakso/server/domain/contest/dto/response/ContestRes.java
  src/main/java/com/gongjakso/server/domain/contest/entity/Contest.java
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepository.java
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/contest/service/ContestService.java
  src/main/java/com/gongjakso/server/global/config/FunctionContributorConfig.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
Labels: feat

#184 fix : 공모전 리스트 응답 데이터 변경
  src/main/java/com/gongjakso/server/domain/contest/dto/response/ContestCard.java
  src/main/java/com/gongjakso/server/domain/contest/service/ContestService.java
Labels: fix

#189 feat : 조회수 기능 구현
  src/main/java/com/gongjakso/server/domain/contest/controller/ContestController.java
  src/main/java/com/gongjakso/server/domain/contest/dto/response/ContestRes.java
  src/main/java/com/gongjakso/server/domain/contest/entity/Contest.java
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepository.java
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/contest/service/ContestService.java
  src/main/java/com/gongjakso/server/global/config/CacheConfig.java
  src/main/java/com/gongjakso/server/global/util/redis/RedisClient.java
Labels: feat
