Repository Gongjakso/server, pull requests merged in 2024-02, with the labels that each got.

#31 feat: post 수정
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/GetProjectRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostDeleteRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostReq.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostRes.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: feat

#27 feat: Category Entity 생성
  src/main/java/com/gongjakso/server/domain/post/entity/Category.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/CategoryType.java
  src/main/java/com/gongjakso/server/domain/post/repository/CategoryRepository.java
Labels: feat

#39 chore: JWT Token 활용할 수 있도록 추가
  src/main/java/com/gongjakso/server/global/config/SwaggerConfig.java
Labels: chore

#37 feat: 출시 알림 받는 API 개발
  src/main/java/com/gongjakso/server/domain/email/controller/EmailController.java
  src/main/java/com/gongjakso/server/domain/email/dto/request/EmailReq.java
  src/main/java/com/gongjakso/server/domain/email/dto/response/EmailRes.java
  src/main/java/com/gongjakso/server/domain/email/entity/Email.java
  src/main/java/com/gongjakso/server/domain/email/repository/EmailRepository.java
  src/main/java/com/gongjakso/server/domain/email/service/EmailService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: feat

#38 feat: 배너 이미지 리스트 반환 API
  src/main/java/com/gongjakso/server/domain/banner/controller/BannerController.java
  src/main/java/com/gongjakso/server/domain/banner/dto/response/BannerRes.java
  src/main/java/com/gongjakso/server/domain/banner/entity/Banner.java
  src/main/java/com/gongjakso/server/domain/banner/enumerate/DomainType.java
  src/main/java/com/gongjakso/server/domain/banner/repository/BannerRepository.java
  src/main/java/com/gongjakso/server/domain/banner/service/BannerService.java
Labels: feat

#33 Feat/apply
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplicationRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/CategoryRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/PeriodReq.java
  src/main/java/com/gongjakso/server/domain/apply/entity/Apply.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/entity/Category.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/CategoryType.java
  src/main/java/com/gongjakso/server/domain/post/repository/CategoryRepository.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: feat, fix

#43 [#4, #6] Post class 게시물 CRUD 구현
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/GetProjectRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostDeleteRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostReq.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostRes.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/MeetingMethod.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/PostStatus.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/main/java/com/gongjakso/server/global/common/BaseTimeEntity.java
Labels: feat

#46 feat: 프로젝트 공고 페이지네이션 및 목록 조회
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/CategoryRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/PeriodReq.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/common/Pagination.java
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/GetProjectRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostReq.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostRes.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/entity/StackName.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/PostType.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/StackNameType.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: feat

#45 Feat/apply
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/PeriodReq.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#50 feat: 최신순 정렬 기능
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/StackNameReq.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/entity/StackName.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: feat

#59 feat: 내정보 반환 API 개발
  src/main/java/com/gongjakso/server/domain/member/controller/MemberController.java
  src/main/java/com/gongjakso/server/global/config/SecurityConfig.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
  src/main/java/com/gongjakso/server/global/security/ExceptionFilter.java
  src/main/java/com/gongjakso/server/global/security/jwt/TokenProvider.java
Labels: feat

#61 feat: 내가 모집중인 팀 리스트 API
  src/main/java/com/gongjakso/server/domain/apply/dto/MyPageRes.java
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/MyPageRes.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: feat

#62 fix: 권한 오류 수정
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#64 feat: 내가 지원한 팀 리스트 반환 API
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
Labels: feat

#65 fix: 공고 상세 조회 API 반환 DTO 수정
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostDetailRes.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#57 feat : 내가 참여한 공고 정보,캘린더 api 기능 구현
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplicationRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyPageRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/PageRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ParticipationList.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ParticipationPageRes.java
  src/main/java/com/gongjakso/server/domain/apply/entity/Apply.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/controller/CalenderController.java
  src/main/java/com/gongjakso/server/domain/post/dto/CalenderRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/ScrapPost.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostScrapRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/CalenderService.java
Labels: feat

#66 fixed : Post API 수정
  src/main/java/com/gongjakso/server/domain/post/dto/GetContestRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/GetProjectRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostReq.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostRes.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/MeetingMethod.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: fix

#68 feat: 스크랩 정보 조회 기능
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: feat

#69 [#63] fixed : ERRORCODE 작성
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: fix

#73 fixed: applyRes DTO 수정
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#74 fix : not-recruit일때 지원 파트 size감소 안되게 수정
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#75 fix : 선발,미선발 api에서 ACCESSToken 요청 삭제
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
Labels: fix

#76 [#60] fix: 공고 상세 조회 API 반환 오류 수정
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#78 fix: CORS 설정 수정
  src/main/java/com/gongjakso/server/global/config/SecurityConfig.java
Labels: fix, chore

#81 fix : 내가 모집 중인 팀 정보 api 공고마감일->활동종료일로 수정
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyRes.java
Labels: fix

#82 fix : my api 지원한 사람 데이터 에서 글 작성자 데이터로 수정
  src/main/java/com/gongjakso/server/domain/apply/dto/MyPageRes.java
Labels: fix

#87 Update README.md
  README.md
Labels: docs
