Repository Gongjakso/server, pull requests merged in 2024-09, with the labels that each got.

#196 feat: Team & Scrap API 개발
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepository.java
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/dto/request/TeamReq.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/SimpleTeamRes.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/TeamRes.java
  src/main/java/com/gongjakso/server/domain/team/entity/Scrap.java
  src/main/java/com/gongjakso/server/domain/team/entity/Team.java
  src/main/java/com/gongjakso/server/domain/team/enumerate/MeetingMethod.java
  src/main/java/com/gongjakso/server/domain/team/enumerate/TeamStatus.java
  src/main/java/com/gongjakso/server/domain/team/repository/ScrapRepository.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepository.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
  src/main/java/com/gongjakso/server/domain/team/vo/RecruitPart.java
  src/main/java/com/gongjakso/server/global/common/Position.java
  src/main/java/com/gongjakso/server/global/config/SecurityConfig.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
  src/main/java/com/gongjakso/server/global/exception/ErrorResponse.java
  src/main/java/com/gongjakso/server/global/exception/GlobalExceptionHandler.java
  src/test/java/com/gongjakso/server/domain/contest/util/ContestUtilTest.java
  src/test/java/com/gongjakso/server/domain/team/service/TeamServiceTest.java
  src/test/java/com/gongjakso/server/domain/team/util/TeamUtilTest.java
Labels: feat

#198 feat: 포트폴리오 CRUD API (공작소 양식) 개발
  build.gradle
  src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/request/PortfolioReq.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/PortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/entity/Portfolio.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
  src/main/java/com/gongjakso/server/domain/portfolio/vo/PortfolioData.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: feat

#201 feat: 포트폴리오 이름 입력 기능 추가
  src/main/java/com/gongjakso/server/domain/portfolio/dto/request/PortfolioReq.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/PortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
  src/main/java/com/gongjakso/server/domain/portfolio/vo/PortfolioData.java
Labels: feat

#199 feat: Apply 관련 기능 개발
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/request/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/request/StatusReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/entity/Apply.java
  src/main/java/com/gongjakso/server/domain/apply/entity/PortfolioInfo.java
  src/main/java/com/gongjakso/server/domain/apply/enumerate/ApplyStatus.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/SimplePortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/entity/Portfolio.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
  src/main/java/com/gongjakso/server/domain/team/entity/Apply.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/gongjakso/server/global/config/SecurityConfig.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: feat

#204 Fix: 포트폴리오 미선택 가능하도록 수정
  src/main/java/com/gongjakso/server/domain/apply/dto/request/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/entity/PortfolioInfo.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/SimplePortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/entity/Portfolio.java
Labels: fix

#207 fix: PortfolioData에서 필드 분리, Education 데이터 타입 변경
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/request/PortfolioReq.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/PortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/SimplePortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/entity/Portfolio.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
  src/main/java/com/gongjakso/server/domain/portfolio/vo/PortfolioData.java
Labels: fix

#208 Fix: 팀 조회 관련 오류 및 예외처리 추가
  src/main/java/com/gongjakso/server/domain/contest/entity/Contest.java
  src/main/java/com/gongjakso/server/domain/team/dto/request/TeamReq.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
Labels: fix

#211 fix : contest body tag
  src/main/java/com/gongjakso/server/domain/contest/service/ContestService.java
Labels: fix

#214 fix: 팀에 대한 사용자 역할 추가 반환
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/TeamRes.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
Labels: fix

#215 fix: Team API 업데이트 및 오류 수정
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/SimpleTeamRes.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/TeamRes.java
  src/main/java/com/gongjakso/server/domain/team/entity/Team.java
  src/main/java/com/gongjakso/server/domain/team/enumerate/TeamStatus.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: fix

#217 fix: 파트 반환하도록 수정
  src/main/java/com/gongjakso/server/domain/team/dto/response/SimpleTeamRes.java
Labels: fix

#220 feat: 스크랩 여부 확인 API
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/ScrapRes.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
Labels: feat

#222 fix: 문의 채널 구분 칼럼 추가
  src/main/java/com/gongjakso/server/domain/team/dto/request/TeamReq.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/TeamRes.java
  src/main/java/com/gongjakso/server/domain/team/entity/Team.java
Labels: fix

#225 feat: 총 스크랩 횟수 반환 API
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/ScrapRes.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/SimpleTeamRes.java
  src/main/java/com/gongjakso/server/domain/team/entity/Team.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
Labels: feat

#223 exist portfolio 관련 api 구현
  src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/ExistPortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/entity/Portfolio.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
Labels: feat

#227 fix: team 조회 시 지원상태면 applyStatus와 applyId 반환하도록 수정
  src/main/java/com/gongjakso/server/domain/apply/enumerate/ApplyStatus.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/TeamRes.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
Labels: fix

#232 fix: Portfolio 타입 반환하도록 수정
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/SimplePortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
Labels: fix

#235 feat: 특정 팀의 지원자 목록 조회 기능 개발
  src/main/java/com/gongjakso/server/domain/apply/dto/response/SimpleApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
Labels: feat

#240 fix : pagenation total size
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
Labels: fix

#243 refactor : query->querydsl로 수정
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryImpl.java
Labels: refactor

#245 fix: QA 사항 업데이트
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: fix

#242 feat: QA사항 반영
  src/main/java/com/gongjakso/server/domain/apply/dto/request/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
  src/main/java/com/gongjakso/server/domain/team/dto/response/TeamRes.java
  src/main/java/com/gongjakso/server/domain/team/entity/Team.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
Labels: feat

#247 fix : exist portfolio delete/find api 수정
  src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/ExistPortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/entity/Portfolio.java
  src/main/java/com/gongjakso/server/domain/portfolio/enumerate/DataType.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: fix

#250 fix: 포트폴리오 권한 및 지원 응답 데이터 변경
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/response/SimpleApplyRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
Labels: fix

#252 fix: ApplyRes 응답 데이터 변경
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
Labels: fix

#253 fix: RecruitPart 반환 추가
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
Labels: fix

#255 fix: 팀 상태 조건 변동사항 적용
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
Labels: fix

#256 fix: ContestId 반환 추가
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
Labels: fix

#257 fix: Portfolio 관련 이슈 해결
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepository.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryImpl.java
Labels: fix

#260 fix : 존재하는 포트폴리오 삭제 오류 수정
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/portfolio/repository/PortfolioRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
Labels: fix

#262 fix : contest update 시 body 문자열 변환
  src/main/java/com/gongjakso/server/domain/contest/entity/Contest.java
Labels: fix

#265 fix: Apply body 데이터 타입 변경
  src/main/java/com/gongjakso/server/domain/apply/entity/Apply.java
Labels: fix

#266 fix: 인기순/조회순 정렬 수정
  src/main/java/com/gongjakso/server/domain/contest/repository/ContestRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/team/controller/TeamController.java
Labels: fix

#267 #249 fix: 포트폴리오 권한 및 응답 데이터 수정
  src/main/java/com/gongjakso/server/domain/apply/dto/request/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/PortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
Labels: fix
