Repository Gongjakso/server, pull requests merged in 2024-10, with the labels that each got.

#268 fix: 지원 시 포트폴리오 관리 수정
  src/main/java/com/gongjakso/server/domain/apply/dto/request/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/response/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/response/SimpleApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/entity/PortfolioInfo.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/PortfolioRes.java
  src/main/java/com/gongjakso/server/domain/portfolio/dto/response/SimplePortfolioRes.java
Labels: fix

#270 refactor: portfolio 오탈자 수정
  src/main/java/com/gongjakso/server/domain/portfolio/controller/PortfolioController.java
  src/main/java/com/gongjakso/server/domain/portfolio/service/PortfolioService.java
Labels: refactor

#274 #273 chore : blue-green 도입
  .github/workflows/release-cd.yml
Labels: chore

#272 fix: Quartz Scheduler 활용하여 팀 상태 변경하기
  .github/workflows/release-cd.yml
  build.gradle
  src/main/java/com/gongjakso/server/domain/team/dto/response/SimpleTeamRes.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryCustom.java
  src/main/java/com/gongjakso/server/domain/team/repository/TeamRepositoryImpl.java
  src/main/java/com/gongjakso/server/domain/team/service/TeamService.java
  src/main/java/com/gongjakso/server/global/config/QuartzConfig.java
  src/main/java/com/gongjakso/server/global/util/quartz/UpdateTeamStatusJob.java
Labels: fix

#276 chore : depoly.sh 도입
  .github/workflows/release-cd.yml
Labels: chore

#278 #273 fix : 띄어쓰기 수정
  .github/workflows/release-cd.yml
Labels: fix

#280 chore : depoly.sh 도입
  .github/workflows/release-cd.yml
Labels: chore
