Repository Gongjakso/server, pull requests merged in 2024-04, with the labels that each got.

#97 Apply 코드 수정
  src/main/java/com/gongjakso/server/domain/apply/controller/ApplyController.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplicationRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/CategoryRes.java
  src/main/java/com/gongjakso/server/domain/apply/entity/Apply.java
  src/main/java/com/gongjakso/server/domain/apply/enumerate/ApplyType.java
  src/main/java/com/gongjakso/server/domain/apply/enumerate/StackType.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/controller/CalendarController.java
  src/main/java/com/gongjakso/server/domain/post/dto/ScrapPost.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/CalendarService.java
  src/main/java/com/gongjakso/server/global/exception/ErrorCode.java
Labels: feat, fix, refactor

#92 fix: post 코드 리팩토링
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/common/Pagination.java
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/dto/CategoryReq.java
  src/main/java/com/gongjakso/server/domain/post/dto/GetContestRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/GetProjectRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostDeleteRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostDetailRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostModifyReq.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostReq.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostScrapRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/ScrapPost.java
  src/main/java/com/gongjakso/server/domain/post/dto/StackNameReq.java
  src/main/java/com/gongjakso/server/domain/post/entity/Category.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/entity/PostScrap.java
  src/main/java/com/gongjakso/server/domain/post/entity/StackName.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix, refactor

#102 Feat/apply
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplicationRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyReq.java
  src/main/java/com/gongjakso/server/domain/apply/entity/Apply.java
  src/main/java/com/gongjakso/server/domain/apply/entity/ApplyStack.java
  src/main/java/com/gongjakso/server/domain/apply/enumerate/StackType.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyRepository.java
  src/main/java/com/gongjakso/server/domain/apply/repository/ApplyStackRepository.java
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/dto/ScrapPost.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/PostStatus.java
  src/main/java/com/gongjakso/server/domain/post/repository/StackNameRepository.java
Labels: feat, fix

#105 [#104] feat: 공고 상세 페이지 조회시, 조회수 반환 기능 추가
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostDetailRes.java
  src/main/java/com/gongjakso/server/domain/post/dto/PostRes.java
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/test/java/com/gongjakso/server/domain/post/service/PostServiceTest.java
Labels: feat

#110 [#104] fix: Post 조회수 조회 및 업데이트 메소드 형태로 수정
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#111 fixed: post 검색 오류 해결
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#109 fix: 사용자 전화번호 칼럼 추가
  build.gradle
  src/main/java/com/gongjakso/server/domain/member/dto/LoginRes.java
  src/main/java/com/gongjakso/server/domain/member/dto/MemberReq.java
  src/main/java/com/gongjakso/server/domain/member/dto/MemberRes.java
  src/main/java/com/gongjakso/server/domain/member/entity/Member.java
  src/test/java/com/gongjakso/server/domain/member/controller/MemberControllerTest.java
  src/test/java/com/gongjakso/server/domain/member/service/MemberServiceTest.java
  src/test/java/com/gongjakso/server/domain/member/util/MemberUtilTest.java
Labels: fix

#112 fix: 모집연장 및 기존 오류 수정
  src/main/java/com/gongjakso/server/domain/post/entity/Post.java
  src/main/java/com/gongjakso/server/domain/post/enumerate/PostStatus.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix, refactor

#113 fix: Transactional 어노테이션 추가
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#117 feat: ApplyRes 사용자 이름 추가
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyRes.java
Labels: feat

#118 feat: ApplicationRes 사용자 이름 추가
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplicationRes.java
  src/main/java/com/gongjakso/server/domain/apply/dto/ApplyRes.java
Labels: fix

#119 Feat/apply
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
  src/main/java/com/gongjakso/server/global/config/SecurityConfig.java
Labels: fix

#121 fix : apply 상태 수정 중 조건 변경
  src/main/java/com/gongjakso/server/domain/apply/service/ApplyService.java
Labels: fix

#122 fix: stackName 필터링 오류 해결
  src/main/java/com/gongjakso/server/domain/post/dto/GetProjectRes.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#124 feat: 내가 스크랩한 프로젝트/공모전 공고 조회 및 페이지네이션 기능 개발Feat/post modified
  src/main/java/com/gongjakso/server/domain/post/controller/PostController.java
  src/main/java/com/gongjakso/server/domain/post/repository/PostScrapRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: feat, fix
