Repository Gongjakso/server, pull requests merged in 2024-06, with the labels that each got.

#160 fix: 모집 연장된 글도 노출되도록 수정
  src/main/java/com/gongjakso/server/domain/post/repository/PostRepository.java
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
Labels: fix

#161 feat: 디스코드 웹훅 연동
  src/main/java/com/gongjakso/server/global/exception/GlobalExceptionHandler.java
  src/main/java/com/gongjakso/server/global/util/discord/DiscordClient.java
Labels: feat

#162 refactor: 공고 생성 빌더 패턴으로 수정
  src/main/java/com/gongjakso/server/domain/post/service/PostService.java
  src/test/java/com/gongjakso/server/domain/post/service/PaginationServiceTest.java
  src/test/java/com/gongjakso/server/domain/post/util/PostUtilTest.java
Labels: refactor

#165 chore: release-cd.yml docker compose 커맨드 수정
  .github/workflows/release-cd.yml
Labels: chore
